
version: '3.0'

services:
  db:
    image: mongo
    restart: always
    volumes:
      - ./db:/data/db
    ports:
      - 27017:27017

  app:
    build:
      context: ./
    restart: always
    volumes:
      - ./frontend:/frontend
      - ./backend:/backend
    image: vue-news
    environment:
      MONGODB_URL: mongodb://db/mydb
    ports:
      - 3000:3000
    entrypoint: /backend/start.sh
    restart: always
